**Numpy**

In [2]:
import numpy as np

In [4]:
myarr = np.array([3,4,5,6,])

In [5]:
myarr

array([3, 4, 5, 6])

In [6]:
myarr.shape

(4,)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0]

3

In [9]:
newarr=np.array([[1,2,3,4,5]])

In [10]:
newarr[0,1]   #accessing the element of 2d array

2

**Array creation : conversion from other python structures**

In [15]:
listarray = np.array([[1,2,3],[6,7,8],[9,0,1]])

In [16]:
listarray

array([[1, 2, 3],
       [6, 7, 8],
       [9, 0, 1]])

In [17]:
listarray.dtype


dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [20]:
listarray.size

9

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
rng = np.arange(10)  #creates a numpy array from 0 to n-1

In [27]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])